version: '3.3'

services:

  on_prem:
    networks:
      - network
    image: ghcr.io/upsonic/on-prem:latest
    volumes:
      - 'On_Prem_Volume:/db'
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000", "&&", "curl", "-f", "http://localhost:3001" ]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  On_Prem_Volume:

networks:
  network:
    external:
      name: on-prem-network
