name: After Push

on: [ push ]


permissions:
  contents: write

jobs:
  select_type:
    if: contains('["onuratakan"]', github.actor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: any_type
        run: |

          commit_msg=$(git log --format=oneline -n 1 $GITHUB_SHA)
          if [[ $commit_msg == *"[PATCH]" ]]; then
            echo "type='PATCH'" >> "$GITHUB_OUTPUT"
          else
            echo "Commit message does not end with [PATCH]"
          fi
    outputs:
      type: ${{ steps.any_type.outputs.type }}


  patch:
    needs: select_type
    runs-on: ubuntu-latest
    if: ${{ needs.select_type.outputs.type }} == 'PATCH'



    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"          

      - name: Run Version Bump Script
        run: python bump.py patch


  patch_build:
    needs: patch
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          
          echo "Commit message ends with [PATCH]"
            curl -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/build.yaml/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "master"}'