name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:


  ubuntu:
    runs-on: ${{ matrix.os }}
    environment: UNIT Tests  
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: nschloe/action-cached-lfs-checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install redis-server
        sudo python -m pip install --upgrade pip
        sudo pip install pytest 
        sudo pip install coverage
        sudo pip3 install -r requirements.txt
        sudo pip3 install -r requirements_2.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest tests && coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Upsonic/On-Prem

